services:


  xteve:
    image: bl0m1/xtevedocker:latest
    network_mode: host
    volumes:
      - type: bind
        source: /srv/dev-disk-by-label-SSD/Configs/xteve
        target: /home/xteve/.xteve
    ports:
      - "34400:34400/tcp"
      - "34400:34400/udp"
    
 
