services:
  vcr:
    image: vcr:latest # local image
    network_mode: bridge
    environment:
      - VBOX_USERNAME=${VBOX_USERNAME}
      - VBOX_PASSWORD=${VBOX_PASSWORD}
      - VBOX_IP=${VBOX_IP}
      - SLEEPTIME=${VBOX_SLEEPTIME}

  xteve:
    image: bl0m1/xtevedocker:latest
    network_mode: bridge
    volumes:
      - type: bind
        source: ${XTEVE_CONFIG_PATH}
        target: /home/xteve/.xteve
    ports:
      - "${XTEVE_PORT}:34400"
    
  plex:
    image: linuxserver/plex:latest
    network_mode: host
    command: --device=/dev/dri:/dev/dri --log-opt max-size=1m
    environment:
      - PUID=${PLEX_PUID}
    volumes:
      - type: bind
        source: /tmp
        target: /transcode
      - type: bind
        source: ${PLEX_CONFIG_PATH}
        target: /config
      - type: bind
        source: ${PLEX_MEDIA_PATH}
        target: /media
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
   
