services:
  vcr:
    image: vcr:latest # local image
    network_mode: bridge
    environment:
      - VBOX_USERNAME=${VBOX_USERNAME}
      - VBOX_PASSWORD=${VBOX_PASSWORD}
      - VBOX_IP=${VBOX_IP}
      - SLEEPTIME=${VBOX_SLEEPTIME}
    restart: unless-stopped

  xteve:
    image: bl0m1/xtevedocker:latest
    volumes:
      - type: bind
        source: ${XTEVE_CONFIG_PATH}
        target: /home/xteve/.xteve
    ports:
      - "${XTEVE_PORT}:34400/tcp"
    networks:
      - media_network
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    devices: 
      - ${PLEX_HW_DEVICE}
    logging:
      options:
        max-size: ${PLEX_MAX_LOG_SIZE}
    environment:
      - PUID=${PLEX_PUID}
      - PGID=${PLEX_PGID}
      - TZ=Europe/Berlin
      - ADVERTISE_IP="192.168.1.254:32400"
    restart: unless-stopped
    networks:
      - media_network
    hostname: Igor
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    links:
      - "xteve:xteve"
    volumes:
      - type: bind
        source: /tmp
        target: /transcode
      - type: bind
        source: ${PLEX_CONFIG_PATH}
        target: /config
      - type: bind
        source: ${PLEX_MEDIA_PATH}
        target: /media
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
   
networks:
  media_network:
    external: false
    name: media_network
