services:
  vcr:
    container_name: VCR
    image: vcr:latest # local image
    network_mode: bridge
    environment:
      - VBOX_USERNAME=${VBOX_USERNAME}
      - VBOX_PASSWORD=${VBOX_PASSWORD}
      - VBOX_IP=${VBOX_IP}
      - SLEEPTIME=${VBOX_SLEEPTIME}

  xteve:
    container_name: xTeVe
    image: bl0m1/xtevedocker:latest
    network_mode: bridge
    volumes:
      - type: bind
        source: ${XTEVE_CONFIG_PATH}
        target: /home/xteve/.xteve
    ports:
      - "${XTEVE_PORT}:34400"
    
